version: '3.8'

includes:
  - database/docker-compose.yml
  - api/docker-compose.yml
  - kafka/docker-compose.yml
  - airflow/docker-compose.yml

services:
  airflow:
    build: 
      context: ./airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    depends_on:
      - postgres
      - kafka

  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./model/models:/app/models
    depends_on:
      - kafka
      - postgres

  kafka:
    build: ./kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 

  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   ports:
  #     - "2181:2181"
