version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: credit-card
      POSTGRES_USER: norbert
      POSTGRES_PASSWORD: 1111
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
