version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: norbert
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: credit-card
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: