services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: credit-card
      POSTGRES_USER: norbert
      POSTGRES_PASSWORD: 4829
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow
    depends_on:
      - postgres
    ports:
      - "8090:8090"
    environment:
      - DB_PASS=4829
      - AIRFLOW_HOME=~/airflow
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8090
      # - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgres://norbert:4829@postgres:5432/credit-card
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      # airflow connections create-default-connections &&
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --firstname Peter --lastname Parker --role Admin --email spiderman@superhero.org --password admin &&
      airflow standalone
      "
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

volumes:
  postgres_data: