FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir kafka-python pandas 

# COPY src/kafka_credit_card_data_producer.py .
# COPY ../model/lr_model.pkl .

# CMD ["python3", "kafka_credit_card_data_producer.py"]