apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: airflow
  labels:
    app: fraud-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
      - name: api
        image: docker.io/apache/airflow:latest
        # imagePullPolicy: Always
        ports:
        - containerPort: 8300
