apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: fraud-detection
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: api
        image: docker.io/apache/kafka
        # imagePullPolicy: Always
        ports:
        - containerPort: 8200
