services:
  fastapi:
    # Uncomment to test pulled FastAPI, lower image lacks ARM Manifest :D
    # image: norbertgrzenkowicz/fraud-api:latest
    build:
      context: ../
      dockerfile: api/Dockerfile
    container_name: fastapi
    ports:
      - "8100:8100"
    # volumes:
    #   - ./api:/code
